### ISSUE TITLE
Future maintainance and first curl issue

### ISSUE THREAD

**Issue by BorlandFA** [segalion/securitasdirect#1]
Hi @segalion 

I just find out about your bash script to use Securitas Direct alarm with Home Assistant since I was planning to develop something similar.
I wanted to ask you if you are still working on this and if you'd feel comfortable if I try to help you on finishing the few TODO's?

Moreover, I have tried it in Mac with no success since the first $CURL does not return any .csv file attachment  and then the grep fails. Any clue?

Thank you very much.

**Comment by segalion** [comment]
Hello. 
This script is a kind of prototyping automation to interact with web access. It has been tested only with spanish web, so the first thing I need to know is your country, as other web can has different versions, or even absolutely different webs. 

This script has been developed reverse engineering spanish web access, as no api is provided by the company.
Another problem could be uncompatibiity bash OSX.
I have a slight integration in HA, with a command-line sensor that pulls state every 60 seconds, and a standard HA alarm module that sync with real alarm, so if you change alarm module, securitas is changed, and if you change securitas, HA alarm module is changed. (I would publish new version with all HA integration as soon as I have a little more spare time).

To improve pull every minute I have discovered that the CSV (that report the last 200 events) is the light form to access securtitas alarm state (The spanish securitas web is very rudimentary and hasnt any websocket suppport).

**Comment by BorlandFA** [comment]
I'm from Spain too and I actually was trying to fake the login as well with Postman and so on, that's why I found your module very interesting since that work was already done!

**Comment by segalion** [comment]
A new custom component has been created. So I close this issue

**Comment by EricBorland** [comment]
Oh great! I'll try it, then
