### ISSUE TITLE
Alarm Mode for Outside

### ISSUE THREAD

**Issue by aladin2000** [segalion/securitasdirect#10]
Hi
I amt not really as ease for coding .. 
As have an alarm system with an extra  external sensors
 that are independent on/off from House or Away Mode
So the number of status for my alarm should be for me : 
states:
  - arm_home
  - arm_away
  - arm_night
  - armed_custom_bypass
So it could be 
- arm_external 
That mode coudl be added to either home  or away status 
Is there a way to easy transforme the Panel and command the alarm in that  mode ?

Do you have some tricks to add that options ?

**Comment by segalion** [comment]
I need to see server responses to identify when a installation has perimetral or anexed sensors...

**Comment by thrice2020** [comment]
Hi, how can I obtain the server responses to send them to you?
Thank you and good job with the component.

David

**Comment by aladin2000** [comment]
hi
Any news about that ?

> I need to see server responses to identify when a installation has perimetral or anexed sensors...

Any news ? 

Fixed  with that code :  (https://img.shields.io/pypi/dm/pysecuritas)

**Comment by aladin2000** [comment]
Fixed with that code : 

https://github.com/Cebeerre/pysecuritas

**Comment by thrice2020** [comment]
Hi! How you did you fix it? I can't see the image,
Thanks.

**Comment by aladin2000** [comment]
> Hi! How you did you fix it? I can't see the image,
> Thanks.

https://github.com/Cebeerre/pysecuritas
