### ISSUE TITLE
Warning on the new 110 version

### ISSUE THREAD

**Issue by barto64** [segalion/securitasdirect#16]
The component record in the log the following WARNING:

2020-05-20 20:43:26 WARNING (MainThread) [homeassistant.components.alarm_control_panel] AlarmControlPanel is deprecated, modify SecuritasAlarm to extend AlarmControlPanelEntity

**Comment by Vartkat** [comment]
Another warning on 110 
<img width="471" alt="image" src="https://user-images.githubusercontent.com/1696899/82515968-ea8fc600-9b19-11ea-9dd3-4eb0eda94ef7.png">

**Comment by Vartkat** [comment]
Warning gone after reboot of serveur (not host as I'm using Docker)

**Comment by segalion** [comment]
Solved with last update
