### ISSUE TITLE
AlarmControlPanel is deprecated, modify SecuritasAlarm to extend AlarmControlPanelEntity

### ISSUE THREAD

**Issue by dafebe** [segalion/securitasdirect#17]
Hi,
since I have updated I see this log.
There is any procedure to fix it?

> Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:194
Integration: Pannello di Controllo degli Allarmi (documentation, issues)
First occurred: 1 luglio 2020, 22:49:31 (1 occurrences)
Last logged: 1 luglio 2020, 22:49:31

AlarmControlPanel is deprecated, modify SecuritasAlarm to extend AlarmControlPanelEntity

**Comment by segalion** [comment]
Solved on latest version
