### ISSUE TITLE
work in command, but i dont the way to integrate in home assistant

### ISSUE THREAD

**Issue by onorbe** [segalion/securitasdirect#3]
hi,

i do step by step your info. but can you describe the way to integrate in homeassistant?

thanks in advance.

**Comment by segalion** [comment]
Sorry about no responese... I am fulltime in other project and have no time...
I have updated bash, upload a little bash to integrate with HA and a little example of ha yaml config...
Sorry, Its not very well documented...

**Comment by segalion** [comment]
A new custom component has been created, based on mobile api. I close this issue
