### ISSUE TITLE
Tested with Verisure Chile

### ISSUE THREAD

**Issue by mjrama** [segalion/securitasdirect#4]
Hi,

I tried you script with Verisure Chile.
Viewing Chile's page I change this parts:
```
HOST="https://customers.verisure.cl"
INSTALL="cl/installations"

tmp=$($CURL $HOST/cl/login/cl -K- <<< "-d \"verisure_rsi_login[nick]=$NICK&verisure_rsi_login[passwd]=$PASSWD&authenticity_token=$token&button=&utf8=\&#x2713;\" -e \"$HOST/\"")

tmp=$($CURL $HOST/cl/remote/job_status/$job_id)
```
Note: in INSTALL and temp I change "es" for "cl" viewing the different pages in Chile. 
I also change Nick and Password.

With that changes I could access my verisure installation, but I coudn't found the .csv file anywhere.

Do you know where exactly is that file? or why I couldn't get it?

P.D: Soy de Chile, podemos hablar en español si quieres.

**Comment by segalion** [comment]
There are a new python CLI and a new custom component for HA. So I close this
